"""
reports.py
Generates a PDF summary report (ReportLab) and CSV exports of the
integrated land records / conflicts / confidence tables.
"""

import io
import datetime
import pandas as pd

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
)
from reportlab.lib.units import cm


def dataframe_to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode("utf-8")


def _df_to_table(df: pd.DataFrame, max_rows=25):
    if df is None or len(df) == 0:
        return Paragraph("No records.", getSampleStyleSheet()["Normal"])
    data = [list(df.columns)] + df.head(max_rows).astype(str).values.tolist()
    table = Table(data, repeatRows=1)
    table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f3a5f")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 7),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f2f4f7")]),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    return table


def build_pdf_report(kpis: dict, conflict_df, confidence_df, resolution_df, validation_summary_dict):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=A4,
                             topMargin=1.5 * cm, bottomMargin=1.5 * cm,
                             leftMargin=1.5 * cm, rightMargin=1.5 * cm)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], textColor=colors.HexColor("#1f3a5f"))
    h2 = ParagraphStyle("H2X", parent=styles["Heading2"], textColor=colors.HexColor("#1f3a5f"))
    normal = styles["Normal"]
    disclaimer_style = ParagraphStyle("Disc", parent=styles["Normal"], fontSize=8, textColor=colors.grey)

    story = []
    story.append(Paragraph("GeoSync AI -- Integration Summary Report", title_style))
    story.append(Paragraph("Intelligent Urban Land Data Integration Platform", normal))
    story.append(Paragraph(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", normal))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(
        "This is an academic / hackathon prototype. It does NOT provide government-certified "
        "accuracy or legal ownership verification. All matches, conflicts and confidence scores "
        "are generated by transparent, rule-based spatial algorithms for demonstration purposes.",
        disclaimer_style))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Key Indicators", h2))
    kpi_data = [[k, str(v)] for k, v in kpis.items()]
    kpi_table = Table(kpi_data, colWidths=[9 * cm, 5 * cm])
    kpi_table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#eef2f7")),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
    ]))
    story.append(kpi_table)
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Validation Summary", h2))
    vs_text = (f"Total features checked: {validation_summary_dict.get('total', 0)} | "
               f"Invalid geometries found: {validation_summary_dict.get('invalid', 0)}")
    story.append(Paragraph(vs_text, normal))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Detected Conflicts", h2))
    story.append(_df_to_table(conflict_df))
    story.append(Spacer(1, 0.5 * cm))

    story.append(PageBreak())
    story.append(Paragraph("Confidence Scoring (per building)", h2))
    story.append(_df_to_table(confidence_df))
    story.append(Spacer(1, 0.5 * cm))

    story.append(Paragraph("Suggested Resolutions", h2))
    story.append(_df_to_table(resolution_df))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()
